// Code generated by "stringer -type=MsgId"; DO NOT EDIT.

package jamulusprotocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[Ackn-1]
	_ = x[JittBufSize-10]
	_ = x[ReqJittBufSize-11]
	_ = x[ChannelGain-13]
	_ = x[ReqConnClientsList-16]
	_ = x[ChatText-18]
	_ = x[NetwTransportProps-20]
	_ = x[ReqNetwTransportProps-21]
	_ = x[ReqChannelInfos-23]
	_ = x[ConnClientsList-24]
	_ = x[ChannelInfos-25]
	_ = x[OpusSupported-26]
	_ = x[LicenceRequired-27]
	_ = x[VersionAndOs-29]
	_ = x[ChannelPan-30]
	_ = x[MuteStateChanged-31]
	_ = x[ClientId-32]
	_ = x[RecorderState-33]
	_ = x[ReqSplitMessSupport-34]
	_ = x[SplitMessSupported-35]
	_ = x[ClmPingMs-1001]
	_ = x[ClmPingMsWithNumClients-1002]
	_ = x[ClmServerFull-1003]
	_ = x[ClmRegisterServer-1004]
	_ = x[ClmUnregisterServer-1005]
	_ = x[ClmServerList-1006]
	_ = x[ClmReqServerList-1007]
	_ = x[ClmSendEmptyMessage-1008]
	_ = x[ClmEmptyMessage-1009]
	_ = x[ClmDisconnection-1010]
	_ = x[ClmVersionAndOs-1011]
	_ = x[ClmReqVersionAndOs-1012]
	_ = x[ClmConnClientsList-1013]
	_ = x[ClmReqConnClientsList-1014]
	_ = x[ClmChannelLevelList-1015]
	_ = x[ClmRegisterServerResp-1016]
	_ = x[ClmRegisterServerEx-1017]
	_ = x[ClmRedServerList-1018]
}

const (
	_MsgId_name_0 = "IllegalAckn"
	_MsgId_name_1 = "JittBufSizeReqJittBufSize"
	_MsgId_name_2 = "ChannelGain"
	_MsgId_name_3 = "ReqConnClientsList"
	_MsgId_name_4 = "ChatText"
	_MsgId_name_5 = "NetwTransportPropsReqNetwTransportProps"
	_MsgId_name_6 = "ReqChannelInfosConnClientsListChannelInfosOpusSupportedLicenceRequired"
	_MsgId_name_7 = "VersionAndOsChannelPanMuteStateChangedClientIdRecorderStateReqSplitMessSupportSplitMessSupported"
	_MsgId_name_8 = "ClmPingMsClmPingMsWithNumClientsClmServerFullClmRegisterServerClmUnregisterServerClmServerListClmReqServerListClmSendEmptyMessageClmEmptyMessageClmDisconnectionClmVersionAndOsClmReqVersionAndOsClmConnClientsListClmReqConnClientsListClmChannelLevelListClmRegisterServerRespClmRegisterServerExClmRedServerList"
)

var (
	_MsgId_index_0 = [...]uint8{0, 7, 11}
	_MsgId_index_1 = [...]uint8{0, 11, 25}
	_MsgId_index_5 = [...]uint8{0, 18, 39}
	_MsgId_index_6 = [...]uint8{0, 15, 30, 42, 55, 70}
	_MsgId_index_7 = [...]uint8{0, 12, 22, 38, 46, 59, 78, 96}
	_MsgId_index_8 = [...]uint16{0, 9, 32, 45, 62, 81, 94, 110, 129, 144, 160, 175, 193, 211, 232, 251, 272, 291, 307}
)

func (i MsgId) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _MsgId_name_0[_MsgId_index_0[i]:_MsgId_index_0[i+1]]
	case 10 <= i && i <= 11:
		i -= 10
		return _MsgId_name_1[_MsgId_index_1[i]:_MsgId_index_1[i+1]]
	case i == 13:
		return _MsgId_name_2
	case i == 16:
		return _MsgId_name_3
	case i == 18:
		return _MsgId_name_4
	case 20 <= i && i <= 21:
		i -= 20
		return _MsgId_name_5[_MsgId_index_5[i]:_MsgId_index_5[i+1]]
	case 23 <= i && i <= 27:
		i -= 23
		return _MsgId_name_6[_MsgId_index_6[i]:_MsgId_index_6[i+1]]
	case 29 <= i && i <= 35:
		i -= 29
		return _MsgId_name_7[_MsgId_index_7[i]:_MsgId_index_7[i+1]]
	case 1001 <= i && i <= 1018:
		i -= 1001
		return _MsgId_name_8[_MsgId_index_8[i]:_MsgId_index_8[i+1]]
	default:
		return "MsgId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
