// Code generated by "stringer -type=SkillLevelId"; DO NOT EDIT.

package jamulusprotocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SkillNone-0]
	_ = x[SkillBeginner-1]
	_ = x[SkillIntermediate-2]
	_ = x[SkillExpert-3]
}

const _SkillLevelId_name = "SkillNoneSkillBeginnerSkillIntermediateSkillExpert"

var _SkillLevelId_index = [...]uint8{0, 9, 22, 39, 50}

func (i SkillLevelId) String() string {
	if i >= SkillLevelId(len(_SkillLevelId_index)-1) {
		return "SkillLevelId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SkillLevelId_name[_SkillLevelId_index[i]:_SkillLevelId_index[i+1]]
}
